#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Oct 22, 2020 03:51:41 PM CEST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import scan_parameters_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    scan_parameters_support.set_Tk_var()
    top = Toplevel1 (root)
    scan_parameters_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    scan_parameters_support.set_Tk_var()
    top = Toplevel1 (w)
    scan_parameters_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("899x778+424+158")
        top.minsize(116, 1)
        top.maxsize(3282, 1174)
        top.resizable(1, 1)
        top.title("Scan Parameters")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.load_btn = tk.Button(top)
        self.load_btn.place(relx=0.011, rely=0.039, height=34, width=129)
        self.load_btn.configure(activebackground="#ececec")
        self.load_btn.configure(activeforeground="#000000")
        self.load_btn.configure(background="#d9d9d9")
        self.load_btn.configure(disabledforeground="#a3a3a3")
        self.load_btn.configure(font="-family {Segoe UI} -size 12")
        self.load_btn.configure(foreground="#000000")
        self.load_btn.configure(highlightbackground="#d9d9d9")
        self.load_btn.configure(highlightcolor="black")
        self.load_btn.configure(pady="0")
        self.load_btn.configure(text='''Load From File''')

        self.Labelframe1 = tk.LabelFrame(top)
        self.Labelframe1.place(relx=0.011, rely=0.125, relheight=0.337
                , relwidth=0.323)
        self.Labelframe1.configure(relief='groove')
        self.Labelframe1.configure(font="-family {Arial} -size 12 -weight bold")
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(text='''Scan''')
        self.Labelframe1.configure(background="#d9d9d9")
        self.Labelframe1.configure(highlightbackground="#d9d9d9")
        self.Labelframe1.configure(highlightcolor="black")

        self.TLabel4_5 = ttk.Label(self.Labelframe1)
        self.TLabel4_5.place(relx=0.034, rely=0.115, height=25, width=48
                , bordermode='ignore')
        self.TLabel4_5.configure(background="#d9d9d9")
        self.TLabel4_5.configure(foreground="#000000")
        self.TLabel4_5.configure(font="-family {Segoe UI} -size 12")
        self.TLabel4_5.configure(relief="flat")
        self.TLabel4_5.configure(text='''B start''')

        self.B_start_etry = tk.Entry(self.Labelframe1)
        self.B_start_etry.place(relx=0.234, rely=0.13, height=20, relwidth=0.29
                , bordermode='ignore')
        self.B_start_etry.configure(background="white")
        self.B_start_etry.configure(disabledforeground="#a3a3a3")
        self.B_start_etry.configure(font="-family {Arial} -size 12")
        self.B_start_etry.configure(foreground="#000000")
        self.B_start_etry.configure(highlightbackground="#d9d9d9")
        self.B_start_etry.configure(highlightcolor="black")
        self.B_start_etry.configure(insertbackground="black")
        self.B_start_etry.configure(selectbackground="#c4c4c4")
        self.B_start_etry.configure(selectforeground="black")

        self.Label1_7 = tk.Label(self.Labelframe1)
        self.Label1_7.place(relx=0.552, rely=0.122, height=24, width=18
                , bordermode='ignore')
        self.Label1_7.configure(activebackground="#f9f9f9")
        self.Label1_7.configure(activeforeground="black")
        self.Label1_7.configure(background="#d9d9d9")
        self.Label1_7.configure(disabledforeground="#a3a3a3")
        self.Label1_7.configure(font="-family {Arial} -size 12")
        self.Label1_7.configure(foreground="#000000")
        self.Label1_7.configure(highlightbackground="#d9d9d9")
        self.Label1_7.configure(highlightcolor="black")
        self.Label1_7.configure(text='''G''')

        self.TLabel5_8 = ttk.Label(self.Labelframe1)
        self.TLabel5_8.place(relx=0.034, rely=0.206, height=25, width=47
                , bordermode='ignore')
        self.TLabel5_8.configure(background="#d9d9d9")
        self.TLabel5_8.configure(foreground="#000000")
        self.TLabel5_8.configure(font="-family {Segoe UI} -size 12")
        self.TLabel5_8.configure(relief="flat")
        self.TLabel5_8.configure(text='''B stop''')

        self.B_stop_etry = tk.Entry(self.Labelframe1)
        self.B_stop_etry.place(relx=0.234, rely=0.221, height=20, relwidth=0.29
                , bordermode='ignore')
        self.B_stop_etry.configure(background="white")
        self.B_stop_etry.configure(disabledforeground="#a3a3a3")
        self.B_stop_etry.configure(font="-family {Arial} -size 12")
        self.B_stop_etry.configure(foreground="#000000")
        self.B_stop_etry.configure(highlightbackground="#d9d9d9")
        self.B_stop_etry.configure(highlightcolor="black")
        self.B_stop_etry.configure(insertbackground="black")
        self.B_stop_etry.configure(selectbackground="#c4c4c4")
        self.B_stop_etry.configure(selectforeground="black")

        self.Label1_3 = tk.Label(self.Labelframe1)
        self.Label1_3.place(relx=0.552, rely=0.218, height=24, width=18
                , bordermode='ignore')
        self.Label1_3.configure(activebackground="#f9f9f9")
        self.Label1_3.configure(activeforeground="black")
        self.Label1_3.configure(background="#d9d9d9")
        self.Label1_3.configure(disabledforeground="#a3a3a3")
        self.Label1_3.configure(font="-family {Arial} -size 12")
        self.Label1_3.configure(foreground="#000000")
        self.Label1_3.configure(highlightbackground="#d9d9d9")
        self.Label1_3.configure(highlightcolor="black")
        self.Label1_3.configure(text='''G''')

        self.TLabel6_4 = ttk.Label(self.Labelframe1)
        self.TLabel6_4.place(relx=0.034, rely=0.298, height=25, width=46
                , bordermode='ignore')
        self.TLabel6_4.configure(background="#d9d9d9")
        self.TLabel6_4.configure(foreground="#000000")
        self.TLabel6_4.configure(font="-family {Segoe UI} -size 12")
        self.TLabel6_4.configure(relief="flat")
        self.TLabel6_4.configure(text='''B step''')

        self.B_step_etry = tk.Entry(self.Labelframe1)
        self.B_step_etry.place(relx=0.234, rely=0.313, height=20, relwidth=0.29
                , bordermode='ignore')
        self.B_step_etry.configure(background="white")
        self.B_step_etry.configure(disabledforeground="#a3a3a3")
        self.B_step_etry.configure(font="-family {Arial} -size 12")
        self.B_step_etry.configure(foreground="#000000")
        self.B_step_etry.configure(highlightbackground="#d9d9d9")
        self.B_step_etry.configure(highlightcolor="black")
        self.B_step_etry.configure(insertbackground="black")
        self.B_step_etry.configure(selectbackground="#c4c4c4")
        self.B_step_etry.configure(selectforeground="black")

        self.Label1_2 = tk.Label(self.Labelframe1)
        self.Label1_2.place(relx=0.552, rely=0.309, height=24, width=18
                , bordermode='ignore')
        self.Label1_2.configure(activebackground="#f9f9f9")
        self.Label1_2.configure(activeforeground="black")
        self.Label1_2.configure(background="#d9d9d9")
        self.Label1_2.configure(disabledforeground="#a3a3a3")
        self.Label1_2.configure(font="-family {Arial} -size 12")
        self.Label1_2.configure(foreground="#000000")
        self.Label1_2.configure(highlightbackground="#d9d9d9")
        self.Label1_2.configure(highlightcolor="black")
        self.Label1_2.configure(text='''G''')

        self.Gaussmeter_checkbutton = tk.Checkbutton(self.Labelframe1)
        self.Gaussmeter_checkbutton.place(relx=0.097, rely=0.439, relheight=0.095
                , relwidth=0.417, bordermode='ignore')
        self.Gaussmeter_checkbutton.configure(activebackground="#ececec")
        self.Gaussmeter_checkbutton.configure(activeforeground="#000000")
        self.Gaussmeter_checkbutton.configure(background="#d9d9d9")
        self.Gaussmeter_checkbutton.configure(disabledforeground="#a3a3a3")
        self.Gaussmeter_checkbutton.configure(font="-family {Arial} -size 12")
        self.Gaussmeter_checkbutton.configure(foreground="#000000")
        self.Gaussmeter_checkbutton.configure(highlightbackground="#d9d9d9")
        self.Gaussmeter_checkbutton.configure(highlightcolor="black")
        self.Gaussmeter_checkbutton.configure(justify='left')
        self.Gaussmeter_checkbutton.configure(text='''Gaussmeter''')
        self.Gaussmeter_checkbutton.configure(variable=scan_parameters_support.che69)

        self.TLabel8_4 = ttk.Label(self.Labelframe1)
        self.TLabel8_4.place(relx=0.034, rely=0.573, height=25, width=77
                , bordermode='ignore')
        self.TLabel8_4.configure(background="#d9d9d9")
        self.TLabel8_4.configure(foreground="#000000")
        self.TLabel8_4.configure(font="-family {Segoe UI} -size 12")
        self.TLabel8_4.configure(relief="flat")
        self.TLabel8_4.configure(text='''Mod. amp.''')

        self.Mod_Amp_etry = tk.Entry(self.Labelframe1)
        self.Mod_Amp_etry.place(relx=0.307, rely=0.595, height=20, relwidth=0.221
                , bordermode='ignore')
        self.Mod_Amp_etry.configure(background="white")
        self.Mod_Amp_etry.configure(disabledforeground="#a3a3a3")
        self.Mod_Amp_etry.configure(font="-family {Arial} -size 12")
        self.Mod_Amp_etry.configure(foreground="#000000")
        self.Mod_Amp_etry.configure(highlightbackground="#d9d9d9")
        self.Mod_Amp_etry.configure(highlightcolor="black")
        self.Mod_Amp_etry.configure(insertbackground="black")
        self.Mod_Amp_etry.configure(selectbackground="#c4c4c4")
        self.Mod_Amp_etry.configure(selectforeground="black")

        self.Gauss_Volt_Combobox = ttk.Combobox(self.Labelframe1)
        self.Gauss_Volt_Combobox.place(relx=0.552, rely=0.595, relheight=0.08
                , relwidth=0.183, bordermode='ignore')
        self.Gauss_Volt_Combobox.configure(takefocus="")

        self.TLabel9_7 = ttk.Label(self.Labelframe1)
        self.TLabel9_7.place(relx=0.034, rely=0.687, height=25, width=74
                , bordermode='ignore')
        self.TLabel9_7.configure(background="#d9d9d9")
        self.TLabel9_7.configure(foreground="#000000")
        self.TLabel9_7.configure(font="-family {Segoe UI} -size 12")
        self.TLabel9_7.configure(relief="flat")
        self.TLabel9_7.configure(text='''Mod. freq.''')

        self.Mod_Freq_etry = tk.Entry(self.Labelframe1)
        self.Mod_Freq_etry.place(relx=0.307, rely=0.695, height=20
                , relwidth=0.221, bordermode='ignore')
        self.Mod_Freq_etry.configure(background="white")
        self.Mod_Freq_etry.configure(disabledforeground="#a3a3a3")
        self.Mod_Freq_etry.configure(font="-family {Arial} -size 12")
        self.Mod_Freq_etry.configure(foreground="#000000")
        self.Mod_Freq_etry.configure(highlightbackground="#d9d9d9")
        self.Mod_Freq_etry.configure(highlightcolor="black")
        self.Mod_Freq_etry.configure(insertbackground="black")
        self.Mod_Freq_etry.configure(selectbackground="#c4c4c4")
        self.Mod_Freq_etry.configure(selectforeground="black")

        self.TLabel1 = ttk.Label(self.Labelframe1)
        self.TLabel1.place(relx=0.552, rely=0.695, height=22, width=33
                , bordermode='ignore')
        self.TLabel1.configure(background="#d9d9d9")
        self.TLabel1.configure(foreground="#000000")
        self.TLabel1.configure(font="-family {Arial} -size 12")
        self.TLabel1.configure(relief="flat")
        self.TLabel1.configure(text='''KHz''')

        self.TSeparator1_6 = ttk.Separator(self.Labelframe1)
        self.TSeparator1_6.place(relx=0.038, rely=0.836, relwidth=0.931
                , bordermode='ignore')

        self.TLabel9_5 = ttk.Label(self.Labelframe1)
        self.TLabel9_5.place(relx=0.034, rely=0.863, height=25, width=74
                , bordermode='ignore')
        self.TLabel9_5.configure(background="#d9d9d9")
        self.TLabel9_5.configure(foreground="#000000")
        self.TLabel9_5.configure(font="-family {Segoe UI} -size 12")
        self.TLabel9_5.configure(relief="flat")
        self.TLabel9_5.configure(text='''# scans''')

        self.nscans_etry = tk.Entry(self.Labelframe1)
        self.nscans_etry.place(relx=0.31, rely=0.882, height=20, relwidth=0.221
                , bordermode='ignore')
        self.nscans_etry.configure(background="white")
        self.nscans_etry.configure(disabledforeground="#a3a3a3")
        self.nscans_etry.configure(font="-family {Arial} -size 12")
        self.nscans_etry.configure(foreground="#000000")
        self.nscans_etry.configure(highlightbackground="#d9d9d9")
        self.nscans_etry.configure(highlightcolor="black")
        self.nscans_etry.configure(insertbackground="black")
        self.nscans_etry.configure(selectbackground="#c4c4c4")
        self.nscans_etry.configure(selectforeground="black")

        self.Labelframe1_3 = tk.LabelFrame(top)
        self.Labelframe1_3.place(relx=0.334, rely=0.125, relheight=0.337
                , relwidth=0.334)
        self.Labelframe1_3.configure(relief='groove')
        self.Labelframe1_3.configure(font="-family {Arial} -size 12 -weight bold")
        self.Labelframe1_3.configure(foreground="black")
        self.Labelframe1_3.configure(text='''Detection''')
        self.Labelframe1_3.configure(background="#d9d9d9")
        self.Labelframe1_3.configure(highlightbackground="#d9d9d9")
        self.Labelframe1_3.configure(highlightcolor="black")

        self.TLabel10 = ttk.Label(self.Labelframe1_3)
        self.TLabel10.place(relx=0.067, rely=0.126, height=25, width=99
                , bordermode='ignore')
        self.TLabel10.configure(background="#d9d9d9")
        self.TLabel10.configure(foreground="#000000")
        self.TLabel10.configure(font="-family {Segoe UI} -size 12")
        self.TLabel10.configure(relief="flat")
        self.TLabel10.configure(text='''Sensitivity''')

        self.TLabel12 = ttk.Label(self.Labelframe1_3)
        self.TLabel12.place(relx=0.067, rely=0.324, height=25, width=118
                , bordermode='ignore')
        self.TLabel12.configure(background="#d9d9d9")
        self.TLabel12.configure(foreground="#000000")
        self.TLabel12.configure(font="-family {Segoe UI} -size 12")
        self.TLabel12.configure(relief="flat")
        self.TLabel12.configure(text='''Conversion time''')

        self.TLabel11 = ttk.Label(self.Labelframe1_3)
        self.TLabel11.place(relx=0.067, rely=0.221, height=25, width=101
                , bordermode='ignore')
        self.TLabel11.configure(background="#d9d9d9")
        self.TLabel11.configure(foreground="#000000")
        self.TLabel11.configure(font="-family {Segoe UI} -size 12")
        self.TLabel11.configure(relief="flat")
        self.TLabel11.configure(text='''Time constant''')

        self.TLabel13 = ttk.Label(self.Labelframe1_3)
        self.TLabel13.place(relx=0.067, rely=0.427, height=25, width=71
                , bordermode='ignore')
        self.TLabel13.configure(background="#d9d9d9")
        self.TLabel13.configure(foreground="#000000")
        self.TLabel13.configure(font="-family {Segoe UI} -size 12")
        self.TLabel13.configure(relief="flat")
        self.TLabel13.configure(text='''Phase''')

        self.TLabel15 = ttk.Label(self.Labelframe1_3)
        self.TLabel15.place(relx=0.067, rely=0.641, height=25, width=75
                , bordermode='ignore')
        self.TLabel15.configure(background="#d9d9d9")
        self.TLabel15.configure(foreground="#000000")
        self.TLabel15.configure(font="-family {Segoe UI} -size 12")
        self.TLabel15.configure(relief="flat")
        self.TLabel15.configure(text='''MW atten.''')

        self.LIA_sens_combobox = ttk.Combobox(self.Labelframe1_3)
        self.LIA_sens_combobox.place(relx=0.5, rely=0.13, relheight=0.08
                , relwidth=0.377, bordermode='ignore')
        self.LIA_sens_combobox.configure(takefocus="")

        self.TC_combobox = ttk.Combobox(self.Labelframe1_3)
        self.TC_combobox.place(relx=0.5, rely=0.229, relheight=0.08
                , relwidth=0.377, bordermode='ignore')
        self.TC_combobox.configure(takefocus="")

        self.LIA_conv_time_combobox = ttk.Combobox(self.Labelframe1_3)
        self.LIA_conv_time_combobox.place(relx=0.5, rely=0.328, relheight=0.08
                , relwidth=0.377, bordermode='ignore')
        self.LIA_conv_time_combobox.configure(takefocus="")

        self.LIA_phase_etry = tk.Entry(self.Labelframe1_3)
        self.LIA_phase_etry.place(relx=0.5, rely=0.447, height=20, relwidth=0.247
                , bordermode='ignore')
        self.LIA_phase_etry.configure(background="white")
        self.LIA_phase_etry.configure(disabledforeground="#a3a3a3")
        self.LIA_phase_etry.configure(font="-family {Arial} -size 12")
        self.LIA_phase_etry.configure(foreground="#000000")
        self.LIA_phase_etry.configure(highlightbackground="#d9d9d9")
        self.LIA_phase_etry.configure(highlightcolor="black")
        self.LIA_phase_etry.configure(insertbackground="black")
        self.LIA_phase_etry.configure(selectbackground="#c4c4c4")
        self.LIA_phase_etry.configure(selectforeground="black")

        self.Label1_1 = tk.Label(self.Labelframe1_3)
        self.Label1_1.place(relx=0.76, rely=0.435, height=24, width=38
                , bordermode='ignore')
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(background="#d9d9d9")
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(font="-family {Arial} -size 12")
        self.Label1_1.configure(foreground="#000000")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="black")
        self.Label1_1.configure(text='''deg''')

        self.MW_freq_etry = ttk.Entry(self.Labelframe1_3)
        self.MW_freq_etry.place(relx=0.367, rely=0.775, relheight=0.08
                , relwidth=0.42, bordermode='ignore')
        self.MW_freq_etry.configure(font="-family {Arial} -size 12")
        self.MW_freq_etry.configure(state='readonly')
        self.MW_freq_etry.configure(takefocus="")
        self.MW_freq_etry.configure(cursor="ibeam")

        self.MW_freq_btn = tk.Button(self.Labelframe1_3)
        self.MW_freq_btn.place(relx=0.057, rely=0.763, height=34, width=79
                , bordermode='ignore')
        self.MW_freq_btn.configure(activebackground="#ececec")
        self.MW_freq_btn.configure(activeforeground="#000000")
        self.MW_freq_btn.configure(background="#d9d9d9")
        self.MW_freq_btn.configure(disabledforeground="#a3a3a3")
        self.MW_freq_btn.configure(font="-family {Segoe UI} -size 12")
        self.MW_freq_btn.configure(foreground="#000000")
        self.MW_freq_btn.configure(highlightbackground="#d9d9d9")
        self.MW_freq_btn.configure(highlightcolor="black")
        self.MW_freq_btn.configure(pady="0")
        self.MW_freq_btn.configure(text='''MW freq.''')

        self.Label1_1 = tk.Label(self.Labelframe1_3)
        self.Label1_1.place(relx=0.8, rely=0.767, height=24, width=38
                , bordermode='ignore')
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(background="#d9d9d9")
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(font="-family {Arial} -size 12")
        self.Label1_1.configure(foreground="#000000")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="black")
        self.Label1_1.configure(text='''GHz''')

        self.Spinbox1 = tk.Spinbox(self.Labelframe1_3, from_=1.0, to=100.0)
        self.Spinbox1.place(relx=0.367, rely=0.656, relheight=0.073
                , relwidth=0.15, bordermode='ignore')
        self.Spinbox1.configure(activebackground="#f9f9f9")
        self.Spinbox1.configure(background="white")
        self.Spinbox1.configure(buttonbackground="#d9d9d9")
        self.Spinbox1.configure(disabledforeground="#a3a3a3")
        self.Spinbox1.configure(font="-family {Arial} -size 12")
        self.Spinbox1.configure(foreground="black")
        self.Spinbox1.configure(highlightbackground="black")
        self.Spinbox1.configure(highlightcolor="black")
        self.Spinbox1.configure(insertbackground="black")
        self.Spinbox1.configure(selectbackground="#c4c4c4")
        self.Spinbox1.configure(selectforeground="black")

        self.TSeparator1 = ttk.Separator(self.Labelframe1_3)
        self.TSeparator1.place(relx=0.033, rely=0.576, relwidth=0.933
                , bordermode='ignore')

        self.Label1_3 = tk.Label(self.Labelframe1_3)
        self.Label1_3.place(relx=0.517, rely=0.645, height=24, width=38
                , bordermode='ignore')
        self.Label1_3.configure(activebackground="#f9f9f9")
        self.Label1_3.configure(activeforeground="black")
        self.Label1_3.configure(background="#d9d9d9")
        self.Label1_3.configure(disabledforeground="#a3a3a3")
        self.Label1_3.configure(font="-family {Arial} -size 12")
        self.Label1_3.configure(foreground="#000000")
        self.Label1_3.configure(highlightbackground="#d9d9d9")
        self.Label1_3.configure(highlightcolor="black")
        self.Label1_3.configure(text='''dB''')

        self.auto_sens_btn = tk.Button(self.Labelframe1_3)
        self.auto_sens_btn.place(relx=0.333, rely=0.126, height=23, width=45
                , bordermode='ignore')
        self.auto_sens_btn.configure(activebackground="#ececec")
        self.auto_sens_btn.configure(activeforeground="#000000")
        self.auto_sens_btn.configure(background="#d9d9d9")
        self.auto_sens_btn.configure(disabledforeground="#a3a3a3")
        self.auto_sens_btn.configure(font="-family {Segoe UI} -size 12")
        self.auto_sens_btn.configure(foreground="#000000")
        self.auto_sens_btn.configure(highlightbackground="#d9d9d9")
        self.auto_sens_btn.configure(highlightcolor="black")
        self.auto_sens_btn.configure(pady="0")
        self.auto_sens_btn.configure(text='''auto''')

        self.auto_phase_btn = tk.Button(self.Labelframe1_3)
        self.auto_phase_btn.place(relx=0.333, rely=0.439, height=23, width=45
                , bordermode='ignore')
        self.auto_phase_btn.configure(activebackground="#ececec")
        self.auto_phase_btn.configure(activeforeground="#000000")
        self.auto_phase_btn.configure(background="#d9d9d9")
        self.auto_phase_btn.configure(disabledforeground="#a3a3a3")
        self.auto_phase_btn.configure(font="-family {Segoe UI} -size 12")
        self.auto_phase_btn.configure(foreground="#000000")
        self.auto_phase_btn.configure(highlightbackground="#d9d9d9")
        self.auto_phase_btn.configure(highlightcolor="black")
        self.auto_phase_btn.configure(pady="0")
        self.auto_phase_btn.configure(text='''auto''')

        self.TLabel1_8 = ttk.Label(self.Labelframe1_3)
        self.TLabel1_8.place(relx=0.89, rely=0.13, height=22, width=23
                , bordermode='ignore')
        self.TLabel1_8.configure(background="#d9d9d9")
        self.TLabel1_8.configure(foreground="#000000")
        self.TLabel1_8.configure(font="-family {Arial} -size 12")
        self.TLabel1_8.configure(relief="flat")
        self.TLabel1_8.configure(text='''V''')

        self.TLabel1_9 = ttk.Label(self.Labelframe1_3)
        self.TLabel1_9.place(relx=0.89, rely=0.225, height=22, width=23
                , bordermode='ignore')
        self.TLabel1_9.configure(background="#d9d9d9")
        self.TLabel1_9.configure(foreground="#000000")
        self.TLabel1_9.configure(font="-family {Arial} -size 12")
        self.TLabel1_9.configure(relief="flat")
        self.TLabel1_9.configure(text='''s''')

        self.TLabel1_4 = ttk.Label(self.Labelframe1_3)
        self.TLabel1_4.place(relx=0.89, rely=0.328, height=22, width=23
                , bordermode='ignore')
        self.TLabel1_4.configure(background="#d9d9d9")
        self.TLabel1_4.configure(foreground="#000000")
        self.TLabel1_4.configure(font="-family {Arial} -size 12")
        self.TLabel1_4.configure(relief="flat")
        self.TLabel1_4.configure(text='''TC''')

        self.Labelframe1_4 = tk.LabelFrame(top)
        self.Labelframe1_4.place(relx=0.667, rely=0.125, relheight=0.337
                , relwidth=0.323)
        self.Labelframe1_4.configure(relief='groove')
        self.Labelframe1_4.configure(font="-family {Arial} -size 12 -weight bold")
        self.Labelframe1_4.configure(foreground="black")
        self.Labelframe1_4.configure(text='''Other''')
        self.Labelframe1_4.configure(background="#d9d9d9")
        self.Labelframe1_4.configure(highlightbackground="#d9d9d9")
        self.Labelframe1_4.configure(highlightcolor="black")

        self.TLabel16 = ttk.Label(self.Labelframe1_4)
        self.TLabel16.place(relx=0.034, rely=0.115, height=25, width=93
                , bordermode='ignore')
        self.TLabel16.configure(background="#d9d9d9")
        self.TLabel16.configure(foreground="#000000")
        self.TLabel16.configure(font="-family {Segoe UI} -size 12")
        self.TLabel16.configure(relief="flat")
        self.TLabel16.configure(text='''Temperature''')

        self.TLabel17 = ttk.Label(self.Labelframe1_4)
        self.TLabel17.place(relx=0.034, rely=0.198, height=25, width=73
                , bordermode='ignore')
        self.TLabel17.configure(background="#d9d9d9")
        self.TLabel17.configure(foreground="#000000")
        self.TLabel17.configure(font="-family {Segoe UI} -size 12")
        self.TLabel17.configure(relief="flat")
        self.TLabel17.configure(text='''Comment''')

        self.Temperature_etry = tk.Entry(self.Labelframe1_4)
        self.Temperature_etry.place(relx=0.379, rely=0.13, height=20
                , relwidth=0.221, bordermode='ignore')
        self.Temperature_etry.configure(background="white")
        self.Temperature_etry.configure(disabledforeground="#a3a3a3")
        self.Temperature_etry.configure(font="-family {Arial} -size 12")
        self.Temperature_etry.configure(foreground="#000000")
        self.Temperature_etry.configure(highlightbackground="#d9d9d9")
        self.Temperature_etry.configure(highlightcolor="black")
        self.Temperature_etry.configure(insertbackground="black")
        self.Temperature_etry.configure(selectbackground="#c4c4c4")
        self.Temperature_etry.configure(selectforeground="black")

        self.Label1_4 = tk.Label(self.Labelframe1_4)
        self.Label1_4.place(relx=0.617, rely=0.122, height=24, width=18
                , bordermode='ignore')
        self.Label1_4.configure(activebackground="#f9f9f9")
        self.Label1_4.configure(activeforeground="black")
        self.Label1_4.configure(background="#d9d9d9")
        self.Label1_4.configure(disabledforeground="#a3a3a3")
        self.Label1_4.configure(font="-family {Arial} -size 12")
        self.Label1_4.configure(foreground="#000000")
        self.Label1_4.configure(highlightbackground="#d9d9d9")
        self.Label1_4.configure(highlightcolor="black")
        self.Label1_4.configure(text='''K''')

        self.Text1 = tk.Text(self.Labelframe1_4)
        self.Text1.place(relx=0.017, rely=0.305, relheight=0.676, relwidth=0.962
                , bordermode='ignore')
        self.Text1.configure(background="white")
        self.Text1.configure(font="-family {Arial} -size 12")
        self.Text1.configure(foreground="black")
        self.Text1.configure(highlightbackground="#d9d9d9")
        self.Text1.configure(highlightcolor="black")
        self.Text1.configure(insertbackground="black")
        self.Text1.configure(selectbackground="#c4c4c4")
        self.Text1.configure(selectforeground="black")
        self.Text1.configure(wrap="word")

        self.set_scan_btn = tk.Button(top)
        self.set_scan_btn.place(relx=0.011, rely=0.476, height=34, width=129)
        self.set_scan_btn.configure(activebackground="#ececec")
        self.set_scan_btn.configure(activeforeground="#000000")
        self.set_scan_btn.configure(background="#d9d9d9")
        self.set_scan_btn.configure(disabledforeground="#a3a3a3")
        self.set_scan_btn.configure(font="-family {Segoe UI} -size 12")
        self.set_scan_btn.configure(foreground="#000000")
        self.set_scan_btn.configure(highlightbackground="#d9d9d9")
        self.set_scan_btn.configure(highlightcolor="black")
        self.set_scan_btn.configure(pady="0")
        self.set_scan_btn.configure(text='''Set CW Scan''')

        self.info_label = ttk.Label(top)
        self.info_label.place(relx=0.011, rely=0.531, height=25, width=214)
        self.info_label.configure(background="#d9d9d9")
        self.info_label.configure(foreground="#000000")
        self.info_label.configure(font="-family {Segoe UI} -size 12")
        self.info_label.configure(relief="flat")
        self.info_label.configure(text='''estimated scan duration: N/A''')

        self.Labelframe2 = tk.LabelFrame(top)
        self.Labelframe2.place(relx=0.011, rely=0.617, relheight=0.366
                , relwidth=0.979)
        self.Labelframe2.configure(relief='groove')
        self.Labelframe2.configure(font="-family {Arial} -size 12 -weight bold")
        self.Labelframe2.configure(foreground="black")
        self.Labelframe2.configure(text='''Electrochemistry''')
        self.Labelframe2.configure(background="#d9d9d9")

        self.TLabel4_6 = ttk.Label(self.Labelframe2)
        self.TLabel4_6.place(relx=0.106, rely=0.211, height=25, width=78
                , bordermode='ignore')
        self.TLabel4_6.configure(background="#d9d9d9")
        self.TLabel4_6.configure(foreground="#000000")
        self.TLabel4_6.configure(font="-family {Segoe UI} -size 12")
        self.TLabel4_6.configure(relief="flat")
        self.TLabel4_6.configure(text='''Low [mV]''')

        self.TLabel4_7 = ttk.Label(self.Labelframe2)
        self.TLabel4_7.place(relx=0.102, rely=0.316, height=25, width=88
                , bordermode='ignore')
        self.TLabel4_7.configure(background="#d9d9d9")
        self.TLabel4_7.configure(foreground="#000000")
        self.TLabel4_7.configure(font="-family {Segoe UI} -size 12")
        self.TLabel4_7.configure(relief="flat")
        self.TLabel4_7.configure(text='''High [mV]''')

        self.TLabel4_8 = ttk.Label(self.Labelframe2)
        self.TLabel4_8.place(relx=0.126, rely=0.421, height=25, width=58
                , bordermode='ignore')
        self.TLabel4_8.configure(background="#d9d9d9")
        self.TLabel4_8.configure(foreground="#000000")
        self.TLabel4_8.configure(font="-family {Segoe UI} -size 12")
        self.TLabel4_8.configure(relief="flat")
        self.TLabel4_8.configure(text='''# steps''')

        self.TLabel4_7 = ttk.Label(self.Labelframe2)
        self.TLabel4_7.place(relx=0.07, rely=0.632, height=25, width=118
                , bordermode='ignore')
        self.TLabel4_7.configure(background="#d9d9d9")
        self.TLabel4_7.configure(foreground="#000000")
        self.TLabel4_7.configure(font="-family {Segoe UI} -size 12")
        self.TLabel4_7.configure(relief="flat")
        self.TLabel4_7.configure(text='''go low [cycles]''')

        self.TLabel4_8 = ttk.Label(self.Labelframe2)
        self.TLabel4_8.place(relx=0.052, rely=0.526, height=25, width=128
                , bordermode='ignore')
        self.TLabel4_8.configure(background="#d9d9d9")
        self.TLabel4_8.configure(foreground="#000000")
        self.TLabel4_8.configure(font="-family {Segoe UI} -size 12")
        self.TLabel4_8.configure(relief="flat")
        self.TLabel4_8.configure(text='''stay high [cycles]''')

        self.electrochem_high_etry = tk.Entry(self.Labelframe2)
        self.electrochem_high_etry.place(relx=0.205, rely=0.333, height=20
                , relwidth=0.186, bordermode='ignore')
        self.electrochem_high_etry.configure(background="white")
        self.electrochem_high_etry.configure(disabledforeground="#a3a3a3")
        self.electrochem_high_etry.configure(font="TkFixedFont")
        self.electrochem_high_etry.configure(foreground="#000000")
        self.electrochem_high_etry.configure(highlightbackground="#d9d9d9")
        self.electrochem_high_etry.configure(highlightcolor="black")
        self.electrochem_high_etry.configure(insertbackground="black")
        self.electrochem_high_etry.configure(selectbackground="#c4c4c4")
        self.electrochem_high_etry.configure(selectforeground="black")

        self.electrochem_steps_etry = tk.Entry(self.Labelframe2)
        self.electrochem_steps_etry.place(relx=0.205, rely=0.439, height=20
                , relwidth=0.186, bordermode='ignore')
        self.electrochem_steps_etry.configure(background="white")
        self.electrochem_steps_etry.configure(disabledforeground="#a3a3a3")
        self.electrochem_steps_etry.configure(font="TkFixedFont")
        self.electrochem_steps_etry.configure(foreground="#000000")
        self.electrochem_steps_etry.configure(highlightbackground="#d9d9d9")
        self.electrochem_steps_etry.configure(highlightcolor="black")
        self.electrochem_steps_etry.configure(insertbackground="black")
        self.electrochem_steps_etry.configure(selectbackground="#c4c4c4")
        self.electrochem_steps_etry.configure(selectforeground="black")

        self.electrochem_stay_high_etry = tk.Entry(self.Labelframe2)
        self.electrochem_stay_high_etry.place(relx=0.205, rely=0.544, height=20
                , relwidth=0.186, bordermode='ignore')
        self.electrochem_stay_high_etry.configure(background="white")
        self.electrochem_stay_high_etry.configure(disabledforeground="#a3a3a3")
        self.electrochem_stay_high_etry.configure(font="TkFixedFont")
        self.electrochem_stay_high_etry.configure(foreground="#000000")
        self.electrochem_stay_high_etry.configure(highlightbackground="#d9d9d9")
        self.electrochem_stay_high_etry.configure(highlightcolor="black")
        self.electrochem_stay_high_etry.configure(insertbackground="black")
        self.electrochem_stay_high_etry.configure(selectbackground="#c4c4c4")
        self.electrochem_stay_high_etry.configure(selectforeground="black")

        self.electrochem_go_low_etry = tk.Entry(self.Labelframe2)
        self.electrochem_go_low_etry.place(relx=0.205, rely=0.646, height=20
                , relwidth=0.186, bordermode='ignore')
        self.electrochem_go_low_etry.configure(background="white")
        self.electrochem_go_low_etry.configure(disabledforeground="#a3a3a3")
        self.electrochem_go_low_etry.configure(font="TkFixedFont")
        self.electrochem_go_low_etry.configure(foreground="#000000")
        self.electrochem_go_low_etry.configure(highlightbackground="#d9d9d9")
        self.electrochem_go_low_etry.configure(highlightcolor="black")
        self.electrochem_go_low_etry.configure(insertbackground="black")
        self.electrochem_go_low_etry.configure(selectbackground="#c4c4c4")
        self.electrochem_go_low_etry.configure(selectforeground="black")

        self.electrochem_set_scan_btn = tk.Button(self.Labelframe2)
        self.electrochem_set_scan_btn.place(relx=0.201, rely=0.796, height=34
                , width=169, bordermode='ignore')
        self.electrochem_set_scan_btn.configure(activebackground="#ececec")
        self.electrochem_set_scan_btn.configure(activeforeground="#000000")
        self.electrochem_set_scan_btn.configure(background="#d9d9d9")
        self.electrochem_set_scan_btn.configure(disabledforeground="#a3a3a3")
        self.electrochem_set_scan_btn.configure(font="-family {Segoe UI} -size 12")
        self.electrochem_set_scan_btn.configure(foreground="#000000")
        self.electrochem_set_scan_btn.configure(highlightbackground="#d9d9d9")
        self.electrochem_set_scan_btn.configure(highlightcolor="black")
        self.electrochem_set_scan_btn.configure(pady="0")
        self.electrochem_set_scan_btn.configure(text='''Set Electrochem Scan''')

        self.electrochem_low_etry = tk.Entry(self.Labelframe2)
        self.electrochem_low_etry.place(relx=0.205, rely=0.235, height=20
                , relwidth=0.186, bordermode='ignore')
        self.electrochem_low_etry.configure(background="white")
        self.electrochem_low_etry.configure(disabledforeground="#a3a3a3")
        self.electrochem_low_etry.configure(font="TkFixedFont")
        self.electrochem_low_etry.configure(foreground="#000000")
        self.electrochem_low_etry.configure(highlightbackground="#d9d9d9")
        self.electrochem_low_etry.configure(highlightcolor="black")
        self.electrochem_low_etry.configure(insertbackground="black")
        self.electrochem_low_etry.configure(selectbackground="#c4c4c4")
        self.electrochem_low_etry.configure(selectforeground="black")

        self.TSeparator1_5 = ttk.Separator(top)
        self.TSeparator1_5.place(relx=0.017, rely=0.605, relwidth=0.968)

if __name__ == '__main__':
    vp_start_gui()





