#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.21
#  in conjunction with Tcl version 8.6
#    Oct 14, 2020 01:45:33 AM CEST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import gui_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    gui_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    gui_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1635x836+252+177")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.btn_open = tk.Button(top)
        self.btn_open.place(relx=0.006, rely=0.012, height=24, width=78)
        self.btn_open.configure(activebackground="#ececec")
        self.btn_open.configure(activeforeground="#000000")
        self.btn_open.configure(background="#d9d9d9")
        self.btn_open.configure(disabledforeground="#a3a3a3")
        self.btn_open.configure(foreground="#000000")
        self.btn_open.configure(highlightbackground="#d9d9d9")
        self.btn_open.configure(highlightcolor="black")
        self.btn_open.configure(pady="0")
        self.btn_open.configure(text='''Open''')

        self.nrm_btn = tk.Button(top)
        self.nrm_btn.place(relx=0.373, rely=0.574, height=24, width=77)
        self.nrm_btn.configure(activebackground="#ececec")
        self.nrm_btn.configure(activeforeground="#000000")
        self.nrm_btn.configure(background="#d9d9d9")
        self.nrm_btn.configure(disabledforeground="#a3a3a3")
        self.nrm_btn.configure(foreground="#000000")
        self.nrm_btn.configure(highlightbackground="#d9d9d9")
        self.nrm_btn.configure(highlightcolor="black")
        self.nrm_btn.configure(pady="0")
        self.nrm_btn.configure(text='''Normalize''')

        self.Viewer_Frame = tk.Frame(top)
        self.Viewer_Frame.place(relx=0.428, rely=0.012, relheight=0.76
                , relwidth=0.56)
        self.Viewer_Frame.configure(relief='sunken')
        self.Viewer_Frame.configure(borderwidth="2")
        self.Viewer_Frame.configure(relief='sunken')
        self.Viewer_Frame.configure(background="#d9d9d9")
        self.Viewer_Frame.configure(highlightbackground="#d9d9d9")
        self.Viewer_Frame.configure(highlightcolor="black")
        self.Viewer_Frame.configure(width=915)

        self.frq_corr = tk.Button(top)
        self.frq_corr.place(relx=0.373, rely=0.538, height=24, width=77)
        self.frq_corr.configure(activebackground="#ececec")
        self.frq_corr.configure(activeforeground="#000000")
        self.frq_corr.configure(background="#d9d9d9")
        self.frq_corr.configure(disabledforeground="#a3a3a3")
        self.frq_corr.configure(foreground="#000000")
        self.frq_corr.configure(highlightbackground="#d9d9d9")
        self.frq_corr.configure(highlightcolor="black")
        self.frq_corr.configure(pady="0")
        self.frq_corr.configure(text='''Freq corr''')

        self.TFrame1 = ttk.Frame(top)
        self.TFrame1.place(relx=0.006, rely=0.096, relheight=0.353
                , relwidth=0.358)
        self.TFrame1.configure(relief='groove')
        self.TFrame1.configure(borderwidth="2")
        self.TFrame1.configure(relief='groove')
        self.TFrame1.configure(width=585)

        self.plt_btn = ttk.Button(top)
        self.plt_btn.place(relx=0.373, rely=0.239, height=25, width=76)
        self.plt_btn.configure(takefocus="")
        self.plt_btn.configure(text='''Plot''')

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.006, rely=0.072, height=21, width=90)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Dataset Browser''')

        self.x_ch_btn = tk.Button(top)
        self.x_ch_btn.place(relx=0.373, rely=0.275, height=34, width=37)
        self.x_ch_btn.configure(activebackground="#ececec")
        self.x_ch_btn.configure(activeforeground="#000000")
        self.x_ch_btn.configure(background="#d9d9d9")
        self.x_ch_btn.configure(disabledforeground="#a3a3a3")
        self.x_ch_btn.configure(foreground="#000000")
        self.x_ch_btn.configure(highlightbackground="#d9d9d9")
        self.x_ch_btn.configure(highlightcolor="black")
        self.x_ch_btn.configure(pady="0")
        self.x_ch_btn.configure(text='''X''')
        self.x_ch_btn.configure(width=37)

        self.y_ch_btn = tk.Button(top)
        self.y_ch_btn.place(relx=0.398, rely=0.275, height=34, width=37)
        self.y_ch_btn.configure(activebackground="#ececec")
        self.y_ch_btn.configure(activeforeground="#000000")
        self.y_ch_btn.configure(background="#d9d9d9")
        self.y_ch_btn.configure(disabledforeground="#a3a3a3")
        self.y_ch_btn.configure(foreground="#000000")
        self.y_ch_btn.configure(highlightbackground="#d9d9d9")
        self.y_ch_btn.configure(highlightcolor="black")
        self.y_ch_btn.configure(pady="0")
        self.y_ch_btn.configure(text='''Y''')
        self.y_ch_btn.configure(width=37)

if __name__ == '__main__':
    vp_start_gui()





